# /* ---- 💫 https://github.com/Fadilix 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/00-Default.conf
# font_family FantasqueSansM Nerd Font Mono Bold
font_size 12.0
# bold_font auto
# italic_font auto
# bold_italic_font auto

# shell /bin/zsh

background_opacity 0.9
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
# Enable trail immediately
cursor_trail 3
cursor_trail_start_threshold 0

# Adjust decay for a longer, more visible "ghost"
cursor_trail_decay 0.08 0.35

# Make the cursor a solid block for maximum thickness
cursor_shape block

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground #dddddd
background #000000
cursor #dddddd

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
