# https://github.com/Fadilix #

$mainMod = SUPER
$files = dolphin
$term =	kitty 
$browser = zen-browser
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$notesApp = obsidian
$codeEditor = code
$calculator = 

# rofi App launcher
bind = $mainMod, D, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window

bind = , key:press, exec, hyprctl keyword input:touchpad:enabled false
bind = , key:release, exec, hyprctl keyword input:touchpad:enabled true

# ags overview
bind = $mainMod, O, exec, $notesApp # launch notes app (Obsidian by default)

bind = $mainMod, Return, exec, $term  # Launch terminal
bind = $mainMod, K, exec, kitty  # Launch Kitty terminal
bind = $mainMod, T, exec, $scriptsDir/launch_kitty_tmux_nvim.sh  # Launch Kitty, check/create tmux session, and run Neovim
bind = $mainMod, E, exec, $files # Launch file manager

# bind = $mainMod, I, exec, qs ipc -c overview call overview toggle
bindd = $mainMod, I,Toggle left panel, exec, qs ipc call config toggle "showRightPanel"
# bindd = $mainMod, I,Toggle left panel, exec, qs ipc call config toggle 

bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh # calculator (qalculate)

# pyprland
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom

# User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme

bind = $mainMod, B, exec, $browser # Launch default browser

bind = $mainMod SHIFT, P, exec, hyprpicker -a / –autocopy # color picker for hyprland

# coding stuff
bind = $mainMod, C, exec, code

# Toggle blue light 
bind = ALT, R, exec, $scriptsDir/ToggleBlueLight.sh

