# https://github.com/Fadilix #
$mainMod = SUPER
$files = dolphin
$term =	kitty 
$browser = zen-browser
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$notesApp = obsidian
$codeEditor = code
$calculator = qalculate-gtk

# rofi App launcher
bind = $mainMod, D, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window

# ags overview
bind = $mainMod, O, exec, $notesApp # launch notes app (Obsidian by default)

bind = $mainMod, Return, exec, $term  # Launch terminal (i never use this 😂)
bind = $mainMod, K, exec, kitty  # Launch Kitty terminal
bind = $mainMod, T, exec, $scriptsDir/launch_kitty_tmux_nvim.sh  # Launch Kitty, check/create tmux session, and run Neovim
bind = $mainMod, E, exec, $files # Launch file manager


bind = , XF86Calculator, exec, $calculator

# pyprland
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom

# User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme

bind = $mainMod, B, exec, $browser # Launch default browser

bind = $mainMod SHIFT, P, exec, hyprpicker -a / –autocopy # color picker for hyprland

# coding stuff
bind = $mainMod, C, exec, code

# Toggle blue light 
bind = ALT, R, exec, $scriptsDir/ToggleBlueLight.sh


# disable mousepad
#
# bind = SUPER, Y, exec, bash -c 'if hyprctl devices -j | grep -q "\"event5\".*\"enabled\": true"; then hyprctl keyword device:event5 enabled false; else hyprctl keyword device:event5 enabled true; fi'
bind = SUPER, Y, exec, $UserScripts/toggle_pointers.sh
